### ISSUE TITLE
Akarin 1.16.1ERROR

### ISSUE THREAD

**Issue by wallace329** [Akarin-project/Akarin#183] opened 2020-08-17 12:07 UTC
`[19:07:31] [Server thread/WARN]: java.lang.NullPointerException
[19:07:31] [Server thread/WARN]: 	at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:58)
[19:07:31] [Server thread/WARN]: 	at com.loohp.interactivechat.Listeners.ChatPackets$1.onPacketSending(ChatPackets.java:92)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:347)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[19:07:31] [Server thread/WARN]: 	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[19:07:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.NetworkManager.writePacket(NetworkManager.java:329)
[19:07:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.NetworkManager.sendPacket(NetworkManager.java:253)
[19:07:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1645)
[19:07:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.sendPacket(PlayerConnection.java:1618)
[19:07:31] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source)
[19:07:31] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:07:31] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:121)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:527)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:509)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:556)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.baltop.perform(baltop.java:82)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:331)
[19:07:31] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:07:31] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:07:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:780)
[19:07:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:466)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.utils.Util.performCommand(Util.java:544)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.utils.Util.performCommand(Util.java:520)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.performCommand(CMI.java:2301)
[19:07:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Economy.EconomyManager$1$2.run(EconomyManager.java:234)
[19:07:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:07:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[19:07:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1345)
[19:07:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:379)
[19:07:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1261)
[19:07:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:993)
[19:07:31] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:164)
[19:07:31] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by LOOHP** [comment] 2020-08-17 16:38
It is caused by Akarin not yet building with latest bungeecord chat API, it has quite a few changes to support new 1.16 chat related stuff.

**Comment by josephworks** [comment] 2020-08-20 00:07
This is fixed in 1.16.2

**Comment by josephworks** [comment] 2020-11-19 21:09
Yep, this is fixed.

**Closed by josephworks** 2020-11-19 21:09 UTC
